format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart007/MOM.res.nc
  hashes:
    binhash: b4b21c535eeee9a1c451422fa571330c
    md5: 28fe39cc1e24b2f89b5d31de49e783be
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart007/MOM.res_1.nc
  hashes:
    binhash: 672b9c721d73a64f66dfd29fcb27bb94
    md5: 007d70be11921bdf5bcd19853123a787
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart007/MOM.res_2.nc
  hashes:
    binhash: d92ebe5dc4d3e216b61910c31734ffff
    md5: 7accbc359e47bc839a9b2d0d0dce93fd
work/INPUT/MOM.res_3.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart007/MOM.res_3.nc
  hashes:
    binhash: 2d8d9be70a77b2f59700903463ad61c4
    md5: 59e8b847524aa9bd0afedeffb9a7fa6d
work/INPUT/MOM.res_4.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart007/MOM.res_4.nc
  hashes:
    binhash: 77af1984cb3852959960c700029abdc0
    md5: 4f41a3e2ae349a1c21da0782f71e1fe1
work/INPUT/MOM.res_5.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart007/MOM.res_5.nc
  hashes:
    binhash: de9432d0bd563b8678b96ad4b2fcb201
    md5: 35c47734aa5957833299958d25ea5c23
work/INPUT/MOM.res_6.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart007/MOM.res_6.nc
  hashes:
    binhash: 6d4c10bec549e22bb410723822d97399
    md5: 72090bf4c82d1e717fd1803dbaec0205
work/INPUT/MOM.res_7.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart007/MOM.res_7.nc
  hashes:
    binhash: eacad0f7534e0aadb99d6f506edffbbd
    md5: ea0d7d0adc7a0d6d294a0a157fce63bc
work/INPUT/MOM.res_8.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart007/MOM.res_8.nc
  hashes:
    binhash: 4225827ff99af394be69c5024675e5ad
    md5: dbd0d44c9581dca1084880cb2aa874dd
work/INPUT/coupler.res:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart007/coupler.res
  hashes:
    binhash: 60afaef8c629dc9c2cdc2467a8445baf
    md5: 7186e0bcc2ba7dc2925930b4f6b9570e
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart007/ice_model.res.nc
  hashes:
    binhash: 84e0edefa65b2c60d39cb70c2c28cca9
    md5: 9571da9a419d677c63b03557abe712dc
