format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart050/MOM.res.nc
  hashes:
    binhash: e6668c0e20e54302a341e7f371c5b0a4
    md5: bf0e2e9dadbfed87c7a990f2624eee73
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart050/MOM.res_1.nc
  hashes:
    binhash: 9010a65efe717f4b1fe7fce64812166b
    md5: 4ac148eb1a5e228887689a903b711b79
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart050/MOM.res_2.nc
  hashes:
    binhash: f9a1c3bc55e76d2f374d17a61500cd85
    md5: d18bfbfcfdf333c935e7b38dc4543aa5
work/INPUT/MOM.res_3.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart050/MOM.res_3.nc
  hashes:
    binhash: e49de09a3e429d78dd864dc846a3edb2
    md5: b34f3dd0b69f106786902bf4e36c9b1b
work/INPUT/MOM.res_4.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart050/MOM.res_4.nc
  hashes:
    binhash: 934a40af318c5b6fc6c1fea779fdef35
    md5: 1f27f8409aa98dada43d4a1f071822fd
work/INPUT/MOM.res_5.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart050/MOM.res_5.nc
  hashes:
    binhash: 030bb3fe39f64f3db515bd4878cbad89
    md5: d707a2cc8bfadf5d2a21aa56d960b963
work/INPUT/MOM.res_6.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart050/MOM.res_6.nc
  hashes:
    binhash: bdd21ec4b2af3c41bfa129d7ebe2d80c
    md5: 0bcf2609d005986118c750a6ecbdbe90
work/INPUT/MOM.res_7.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart050/MOM.res_7.nc
  hashes:
    binhash: 084d0d69dea71ae1930e5bd27bcbc1d4
    md5: 9bd9a6a152faa3f80d01a65ee4805cd3
work/INPUT/MOM.res_8.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart050/MOM.res_8.nc
  hashes:
    binhash: 04153f189462acd1b1d679b5ed010ab8
    md5: 59ee66411726b3b719340554ffc0fae3
work/INPUT/coupler.res:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart050/coupler.res
  hashes:
    binhash: 4a190cdee7cd62081dff3614609c090c
    md5: 91d976c3c552a6b7b50b6ce907e8b744
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart050/ice_model.res.nc
  hashes:
    binhash: 3a16ca89acb76219c7c28f10e5ba32c6
    md5: abf42f62e4433fb12d74b18b0f6e5ebb
