format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart036/MOM.res.nc
  hashes:
    binhash: 7dcaeea1fc22b076af63b2a965db4d6f
    md5: f20c5ea7322afef8cdbdaa3929eae823
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart036/MOM.res_1.nc
  hashes:
    binhash: 558894f8f475f608db3345db5e9f3036
    md5: b5cba51ceac9f56afc891563bc3ae8d8
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart036/MOM.res_2.nc
  hashes:
    binhash: 89df2deb541aec6f9ecca91c0424e0f7
    md5: c88ac78376c424bf474efe8f57678779
work/INPUT/MOM.res_3.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart036/MOM.res_3.nc
  hashes:
    binhash: 60d4b46e3c2264f3d61800d2f69f4a3f
    md5: 03504fdb4106168a66cbcced8721aa99
work/INPUT/MOM.res_4.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart036/MOM.res_4.nc
  hashes:
    binhash: 9b6a9eafe6af8c13fe2863988fab04b7
    md5: f0bdc5e8271dde4164cc842b2e51a8a6
work/INPUT/MOM.res_5.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart036/MOM.res_5.nc
  hashes:
    binhash: 6f085b3a474a3819524f6fb5e032b085
    md5: 3afd377903d3e818b227f7535373823f
work/INPUT/MOM.res_6.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart036/MOM.res_6.nc
  hashes:
    binhash: fd7e78844e13dec2f5c1b01f0e260d04
    md5: cbce0d0ece617e89cdbbe58ded35f99f
work/INPUT/MOM.res_7.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart036/MOM.res_7.nc
  hashes:
    binhash: 4de2cf43da333aa6530612a6df7d4e91
    md5: 2af9a7ad53ed11a4872d64d6313273f4
work/INPUT/MOM.res_8.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart036/MOM.res_8.nc
  hashes:
    binhash: c205ad330850d8bf3c45f159d28d52e9
    md5: bc6e516963cd0bb42515f66e7d21a5ce
work/INPUT/coupler.res:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart036/coupler.res
  hashes:
    binhash: c7d42f6347b3367646375e125bac1189
    md5: be0cbfcabc751ae10f007191da3fca97
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart036/ice_model.res.nc
  hashes:
    binhash: 2b9f32ecda4a40fd0075c62340d1d629
    md5: 1dc92a9e1765da24f40902bc7e5b368d
