format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/MOM.res.nc
  hashes:
    binhash: cbc880d24baf05dbd3cdcc4b235e8d49
    md5: 839b19ccca60e1d216ee81da6fc98b83
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/MOM.res_1.nc
  hashes:
    binhash: cc6af84b8966a8678ef07740d446bb8b
    md5: 2621203629fbccf21b89e62cb1cf3f87
work/INPUT/MOM.res_10.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/MOM.res_10.nc
  hashes:
    binhash: 996c79ae27de89014f4796a1b45571b1
    md5: e9814b5c578012cf49eb3301ab1e2f09
work/INPUT/MOM.res_11.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/MOM.res_11.nc
  hashes:
    binhash: 6accdc27a4b9ff10cf5b814b0b8c5984
    md5: 578edb03722ce1b6d309f5913399bc91
work/INPUT/MOM.res_12.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/MOM.res_12.nc
  hashes:
    binhash: d4a68b35e39fdb69c74d20e5b490d2ec
    md5: 3ddf6d4af6db8b71a90b6cfa0d8008ef
work/INPUT/MOM.res_13.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/MOM.res_13.nc
  hashes:
    binhash: d67bf4bc75e2a8e9cbde45fdc609ff06
    md5: 49a0cfbd0f2b9a5ca19b01aafff66e45
work/INPUT/MOM.res_14.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/MOM.res_14.nc
  hashes:
    binhash: b1d0f0cfdcac9247be8e42885408b60c
    md5: a9bdd6d57a1de950a7d043e4591dfba7
work/INPUT/MOM.res_15.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/MOM.res_15.nc
  hashes:
    binhash: 206c5cc16bf3814f99250038344b1c88
    md5: d9400f41d2129da717e6ccccbffbcd6f
work/INPUT/MOM.res_16.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/MOM.res_16.nc
  hashes:
    binhash: 46e50a79c3d13229ea42a0761b3fdb8e
    md5: 01bb099d58c78a5da49c7eb0386d4add
work/INPUT/MOM.res_17.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/MOM.res_17.nc
  hashes:
    binhash: 2c2749fe02e2fdf5c0f7c26501400cb8
    md5: 75afd45954dff3c42de3b2ed14daaa46
work/INPUT/MOM.res_18.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/MOM.res_18.nc
  hashes:
    binhash: 64b2ed8350d82d8539551b4d02b1ff86
    md5: 70989b61b6cdd1a9a85bbbcfbb81220a
work/INPUT/MOM.res_19.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/MOM.res_19.nc
  hashes:
    binhash: 1c28493b790badc1ade2d5b16905bc7a
    md5: 041c59065e61856b7b0f70fefaa5f08b
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/MOM.res_2.nc
  hashes:
    binhash: f2bd4fc38c20a73f3da04bc77e4d61a1
    md5: 14c143e82f9ec33c5a1fefe7a1580b6e
work/INPUT/MOM.res_20.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/MOM.res_20.nc
  hashes:
    binhash: e107796c612d2ac9f1cd8c663c56864a
    md5: a49852207dd581bf50b2984e4376b8ec
work/INPUT/MOM.res_3.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/MOM.res_3.nc
  hashes:
    binhash: 6cde75294d1eb95c9b6cc5717f62d14f
    md5: c17532dbb6f3b858d9493af046065b18
work/INPUT/MOM.res_4.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/MOM.res_4.nc
  hashes:
    binhash: 20dbff855f0865cb3b27fa15c7616aa6
    md5: 739f6060e50b7ac27e2ee62285d324e1
work/INPUT/MOM.res_5.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/MOM.res_5.nc
  hashes:
    binhash: ad52c906e99e908f2bbcbd4796f4c49c
    md5: 1441e5b5b48a4283c6b33257b43c3225
work/INPUT/MOM.res_6.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/MOM.res_6.nc
  hashes:
    binhash: c9f519bf299a9a1ab2d97c09445cc259
    md5: b9cdee891b5414328eddad6ed45931da
work/INPUT/MOM.res_7.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/MOM.res_7.nc
  hashes:
    binhash: f8e1f8ba47f15b4a14a16a1ed739d478
    md5: 8f9f4a5aa355f61591a89f032e14caca
work/INPUT/MOM.res_8.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/MOM.res_8.nc
  hashes:
    binhash: db837000b00ad748d8df6e6bec4f5f2d
    md5: a031b425cc92a8e8e4a9fc9318b03e57
work/INPUT/MOM.res_9.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/MOM.res_9.nc
  hashes:
    binhash: 8eb295ec3fa7b0616a413ae8f74a931a
    md5: 2125d1f3641ad282252b4a9852d933cb
work/INPUT/coupler.res:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/coupler.res
  hashes:
    binhash: e41f93b643cab1e34b880f1fdb5df883
    md5: da4e96782e55bec5a2ee48b5b9608d3d
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/mom6-panan-hycom1/restart032/ice_model.res.nc
  hashes:
    binhash: 5fa33bba54a96ea43cc11016beea2771
    md5: 94dc3066a6ade5b7f9104feca14c16fe
