format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart025/MOM.res.nc
  hashes:
    binhash: bedc26b11c608f3a4951c95b9cb776ce
    md5: 6eaef0d19a8754b7d087bd8dd035a074
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart025/MOM.res_1.nc
  hashes:
    binhash: 476ad6a05a27c5cd2d0b29c64cd45726
    md5: 811efde5150228e20549e15b31930040
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart025/MOM.res_2.nc
  hashes:
    binhash: 29707ceaea1dfa7b6e3073129f6eaf00
    md5: e1426bdac6446aae32db693b588f5f35
work/INPUT/MOM.res_3.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart025/MOM.res_3.nc
  hashes:
    binhash: ce2a514ad4e5586ee6025bb0ebb8f13e
    md5: 1c01ea5dfeb2bc2b6b09e438b4f97105
work/INPUT/MOM.res_4.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart025/MOM.res_4.nc
  hashes:
    binhash: b60dfb888c1d3ab230bd433ca674906e
    md5: ed2f6bec3a4d2fa90549c196fc25693e
work/INPUT/MOM.res_5.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart025/MOM.res_5.nc
  hashes:
    binhash: 0150a8adb647a070d419b7c0662e7d9e
    md5: b7334d38693d81e2412af1934bca7fe7
work/INPUT/MOM.res_6.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart025/MOM.res_6.nc
  hashes:
    binhash: 884fbd2d0a2459f7661b7ca17bc9784b
    md5: 7773f2b179cdaedefbd89fe0908ae8a7
work/INPUT/MOM.res_7.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart025/MOM.res_7.nc
  hashes:
    binhash: 33ac5527e603d445bc12f66285132f78
    md5: a83c6ce26fff45b939a9b10be6de3d0d
work/INPUT/MOM.res_8.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart025/MOM.res_8.nc
  hashes:
    binhash: feade0b02cd2dca5449ce3bba2f1bc49
    md5: a112d2cb098e18f00b8fe172fcc8e1be
work/INPUT/coupler.res:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart025/coupler.res
  hashes:
    binhash: 7c5bf14ca7ba535ecc22564bfa5909cf
    md5: b51e2cc6321706c06d9850030e7e9d64
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-zstar/restart025/ice_model.res.nc
  hashes:
    binhash: 741532d8a5f63212745f5d28ce734e34
    md5: 88ed1ded363b48716a5b7e67dfe12a4a
