format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart037/MOM.res.nc
  hashes:
    binhash: 98a44eeeb29b227c86e524bda3da252d
    md5: a4be9e08b466a0c8e63effb0532adec8
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart037/MOM.res_1.nc
  hashes:
    binhash: 2c151ce1c811fbfdfaee36ab4a3401c7
    md5: 89c5b28cafc4f67c5d10bd48e12d1e7b
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart037/MOM.res_2.nc
  hashes:
    binhash: 8597e419d73a61d5f4ba7ccebdbdd2a9
    md5: 8a6f9a7680b2079d21bfb577d0049509
work/INPUT/MOM.res_3.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart037/MOM.res_3.nc
  hashes:
    binhash: d9a42cd98e93af28e43cb3698c6b6aa3
    md5: b1f51e2349bff6bcaa5d280a8da74632
work/INPUT/MOM.res_4.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart037/MOM.res_4.nc
  hashes:
    binhash: 48fbd7256577340e67d70e4fca45c464
    md5: 911334b4d379385381fbd307347a3a9d
work/INPUT/MOM.res_5.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart037/MOM.res_5.nc
  hashes:
    binhash: 8f075925607edee948dec7cc72c46c3b
    md5: 3fbccfb0f0c60a4dc595074d7c6aa03e
work/INPUT/MOM.res_6.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart037/MOM.res_6.nc
  hashes:
    binhash: e3962183c6809fdd26b536982887dd1c
    md5: 04ee1a83a9a47e22d75919d9ba372e20
work/INPUT/MOM.res_7.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart037/MOM.res_7.nc
  hashes:
    binhash: 45dd0b70c9febba8f02b29fe8daf1128
    md5: eb32a8e72beb1f03927d2b6c5e3d283e
work/INPUT/MOM.res_8.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart037/MOM.res_8.nc
  hashes:
    binhash: bfc381bcbc12da835bb96964acb08658
    md5: a4cc84603c61f0088a1ae09000ba033e
work/INPUT/coupler.res:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart037/coupler.res
  hashes:
    binhash: cf889fdb27e27d926eb3344a07c9d184
    md5: a602ce524ab0de4ff608c7056e190795
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/x77/amh157/mom6/archive/panan-01-hycom1/restart037/ice_model.res.nc
  hashes:
    binhash: 87c840be1ff73bdb6f6ab38ef6c68e6c
    md5: a3e7498f8eb56db26f8b93fba68f0c20
